apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
     name: kanna-user-binding
     namespace: testing
subjects:
      -  kind : User
         name: kanna
         apiGroup:  rbac.authorization.k8s.io
roleRef:
        kind: Role
        name: mymonitor-role
        apiGroup:  rbac.authorization.k8s.io